### ISSUE TITLE
请问下UP主，如何格式化这种js代码？我打开GitHubDesktop的main.js  显示一团糟

### ISSUE THREAD

**Issue by asisbai** [lkyero/GitHubDesktop_zh#2]
请问下UP主，如何格式化这种js代码？我打开GitHubDesktop的main.js  显示一团糟

**Comment by lkyero** [comment]
> 请问下UP主，如何格式化这种js代码？我打开GitHubDesktop的main.js 显示一团糟

使用的【`VSCode`】应用商店插件`【Beautify`】，作者`HookyQR`的辣个
安装插件，打开.js文件，点击F1—选择Beautify file。
（附上插件GIT：https://github.com/HookyQR/VSCodeBeautify ）

**Comment by asisbai** [comment]
谢谢
