### ISSUE TITLE
汉化后白屏

### ISSUE THREAD

**Issue by acai1998** [lkyero/GitHubDesktop_zh#70]
![image](https://github.com/user-attachments/assets/7f4ae301-71c5-404c-aa80-e43c52684b6c)
![image](https://github.com/user-attachments/assets/f1133bd7-9421-476f-a2f2-156766f58739)
[
![Snipaste_2024-08-04_18-13-11](https://github.com/user-attachments/assets/23afbfb8-6ce6-44e7-9d7b-b2e5eec61e04)
](url)

**Comment by mwoldlee** [comment]
俺也一样

**Comment by zcmsx1** [comment]
+1

**Comment by Xqinyue** [comment]
+1

**Comment by Xqinyue** [comment]
查清楚了 要版本一致不然白屏

**Comment by zetaloop** [comment]
版本不对应，直接替换 main.js 和 renderer.js 会导致功能出错。
这里作者可能弃坑了，试试我的？[zetaloop/Desktop](https://github.com/zetaloop/Desktop)

**Comment by 743859910** [comment]
你们用的时候也不看人家最后一次什么时候更新的
